# Docker for Mezzanine CMS + REST API
version: '2'

services:
  # A microservice for the web app.
  web:
    container_name: web
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./web/static:/usr/src/app/static
      - ./web/static/media:/usr/src/app/static/media
    env_file: .env
    command: /start.sh

  # A microservice for the web server.
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/static
      - /www/static/media
    volumes_from:
      - web
    links:
      - web:web

  # A microservice for the database.
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    #volumes:
    #  - pgdata:/var/lib/postgresql/data/
